add deployment health check and rollback

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -166,7 +166,22 @@ jobs:
               key: ${{ secrets.EC2_SSH_KEY }}
               script: |
                 cd ~/devops-production-app
+                CURRENT_TAG=$(GREP '^IMAGE_TAG=' .env | cut -d '=' -f2)
+                
+                echo "Current image tag: $CURRENT_TAG"
+                echo "New image tag: ${{ github.sha }}"
                 sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ github.sha }}/" .env
                 docker compose -f docker-compose.prod.yml pull
                 docker compose -f docker-compose.prod.yml up -d
+                sleep 10
+                if ! curl --fail http://localhost/api/health; then
+                  echo "Health check failed!"
+                  echo "Rolling back to $CURRENT_TAG"
+
+                  sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=$CYRRENT_TAG/" .env
+                  docker compose -f docker-compose.prod.yml pull
+                  docker compose -f docker-compose.prod.yml up -d
+                  exit 1
+                fi
+                echo "Deployment successful!"
                 docker compose -f docker-compose.prod.yml ps
